export const PARKING_CATEGORIES = [
  {
    id: 1,
    label: 'Standardno',
    description: 'Obično parkirno mjesto za osobna vozila.',
    icon: '🚗',
    color: '#A8D5BA',
  },
  {
    id: 2,
    label: 'Invalidsko',
    description: 'Rezervirano za osobe s invaliditetom.',
    icon: '♿',
    color: '#AFCBFF',
  },
  {
    id: 3,
    label: 'Električna vozila',
    description: 'Parkirno mjesto s punjačem za EV.',
    icon: '🔌',
    color: '#B3E5FC',
  },
  {
    id: 4,
    label: 'Obiteljsko',
    description: 'Prošireno mjesto za obitelji s djecom.',
    icon: '👨‍👩‍👧‍👦',
    color: '#FFD3B6',
  },
  {
    id: 5,
    label: 'Kratkotrajno',
    description: 'Za brzo parkiranje do 15 minuta.',
    icon: '⏱️',
    color: '#D7BDE2',
  },
  {
    id: 6,
    label: 'Dugotrajno',
    description: 'Namijenjeno za višesatno parkiranje.',
    icon: '🕒',
    color: '#D6DBDF',
  },
  {
    id: 7,
    label: 'Motocikli',
    description: 'Parkirno mjesto za motocikle i skutere.',
    icon: '🏍️',
    color: '#F8BBD0',
  },
  {
    id: 8,
    label: 'Teretna vozila',
    description: 'Za kombije, kamione i dostavna vozila.',
    icon: '🚚',
    color: '#FFCCBC',
  },
  {
    id: 9,
    label: 'VIP',
    description: 'Rezervirano za goste s posebnom dozvolom.',
    icon: '⭐',
    color: '#FFF9C4',
  },
  {
    id: 10,
    label: 'Zatvoreno',
    description: 'Mjesto trenutno nije dostupno.',
    icon: '🚫',
    color: '#FFCDD2',
  },
  {
    id: 11,
    label: 'Rezervirano',
    description: 'Parkirno mjesto rezervirano za određenog korisnika.',
    icon: '🔒',
    color: '#D1C4E9',
  },
  {
    id: 12,
    label: 'Podzemno',
    description: 'Nalazi se u garaži ispod površine.',
    icon: '🏢',
    color: '#B0BEC5',
  },
  {
    id: 13,
    label: 'Nadzemno',
    description: 'Otvoreno parkirno mjesto iznad zemlje.',
    icon: '🌤️',
    color: '#B2EBF2',
  },
  {
    id: 14,
    label: 'Noćno',
    description: 'Dostupno samo noću (npr. 20:00-06:00).',
    icon: '🌙',
    color: '#C5CAE9',
  },
  {
    id: 15,
    label: 'Punjenje bicikala',
    description: 'Mjesto za električne bicikle s punjačem.',
    icon: '🚲',
    color: '#DCEDC8',
  },
];
